### PR TITLE
Adding Axios Reference To package.json

### PR DESCRIPTION
**Pull request by ca1c**
adding axios reference so that `yarn add` automatically installs axios.

### CODE REVIEW

**Comment by katrinar** [comment]
Thanks for the PR! Good catch on adding `axios` to the `package.json`.

To merge this in, would you mind removing the styling changes and only including the `package.json` and `yarn.lock` changes? At this stage, we're looking to keep the styling minimal.

**Comment by ca1c** [comment]
No problem I will do that

**Comment by ca1c** [comment]
The style commit was removed although there are still conflicts.

**Comment by katrinar** [comment]
Thanks for making the changes! We got `axios` in earlier with [this PR](https://github.com/golivecosmos/llm-react-node-app-template/commit/dff745e1812975dc02cbbd7e5b13a77cd60ca447#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) so I'll go ahead and close this one.

**Pull request closed without merging**
